name: Docker

on:
  release:
    types: [published]
    branches: ["main", "master", "dev-*", "nightly", "staging-*", "release-*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: nelonoel/branch-name@v1.0.1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ci.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER }}/${{ secrets.DOCKER_HUB_REPO }}:${{ env.BRANCH_NAME }}
          build-args: |
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Edit Release
        uses: irongut/EditRelease@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ github.event.release.id }}
          body: "Docker: ${{ secrets.DOCKER_HUB_USER }}/${{ secrets.DOCKER_HUB_REPO }}:${{ env.BRANCH_NAME }}"